### ISSUE TITLE
[Questions] Use in animations

### ISSUE THREAD

**Issue by 2Dimm** [Pauan/blender-rigid-body-bones#1]
I dont really have a issue with the addon, its actually probably the most complete rigid body bone addon out there! i just have a question... is the only way to work with this is every animation has to start as a "T pose" and then move the character into wherever position you want or am i missing something? since directly starting on a pose that is not the base pose will just make the bones simulate in the starting position anyway
![hair](https://user-images.githubusercontent.com/20032676/108612225-506cef00-73c5-11eb-922d-12a21febbda1.png)

**Comment by Pauan** [comment]
I think this is just how Blender handles rigid bodies in general, so I don't think there's anything this add-on can do about it, it just creates rigid bodies and lets Blender handle everything else.

But I'll look into it and see if maybe I can improve it somehow.

**Comment by Pauan** [comment]
So after several days of work, I completely redid how the system works, but I managed to fix this.

In [version 1.5.0](https://github.com/Pauan/blender-rigid-body-bones/releases/tag/v1.5.0) if you change the position of the bones in Pose mode then it will use that for the simulation. But this only works on frame 1.
