### ISSUE TITLE
Question: Is there default settings figured out for different physics?

### ISSUE THREAD

**Issue by Graem117** [Pauan/blender-rigid-body-bones#12]
Has someone figure out default settings for breast, hair, butt, ect ect physics? Be nice to get a base to help get started using it.

**Comment by Pauan** [comment]
I think that will depend on a lot of things: how big the bones are, how they are weight painted, the position of the bones, the shape and size of the body parts, etc.

If somebody wants to try and figure out common values, I think that would be useful.

**Comment by Graem117** [comment]
Ya been searching around for any details since it has been out for a long time, figure somone would post it by now. Unless theres a model already out there that has the settings to be used for reference, that could help too.

**Comment by Pauan** [comment]
The [Kizuna AI example](https://github.com/Pauan/blender-rigid-body-bones/tree/master/Rigid%20Body%20Bones/examples) does have some. I normally just play around with the settings until I get something that looks good.

**Comment by Graem117** [comment]
Oh wait

**Comment by Graem117** [comment]
The kizuna example is acting wierd
![image](https://user-images.githubusercontent.com/67132870/154441001-75a20cd5-66b0-4181-8aed-ac426867a8bd.png)

**Comment by Graem117** [comment]
I am blender 3.0 right now, did that update affect the add-on?

**Comment by Graem117** [comment]
Ah its just a wierd texture bug, it looks better in the animation tab.

**Comment by Pauan** [comment]
Sometimes weird things happens with the baking, so you should do `Rigid Body World` -> `Cache` -> `Delete All Bakes`.

And then do `Rigid Body World` -> `Cache` -> `Bake All Dynamics` to rebake it.

**Comment by Graem117** [comment]
Ya that made it better, and after going through the example I got a better understanding of the settings now. Thanks!
