### ISSUE TITLE
Can't even get basics to work

### ISSUE THREAD

**Issue by Fowlet** [Pauan/blender-rigid-body-bones#16]
I have a rigged humanoid I'm trying to add physics to. If I use this plugin to make e.g. only a finger an active rigid body, it works as expected. However, if I make e.g. the palm and one finger (parent and child) active bodies, nothing moves. Am I missing something?

![image](https://user-images.githubusercontent.com/8314531/164308717-35358e28-d6c7-4d8a-8b2b-331d6f15896a.png)

**Comment by Pauan** [comment]
@Fowlet Could you please share your `.blend` file?

**Comment by Fowlet** [comment]
I'm an idiot, I had old rigid bodies from my previous manual attempts at adding physics, that overlapped the new bone rigid bodies, so they refused to move. Thanks!
