### ISSUE TITLE
Blender rigid body bones, not working on blender 3.5

### ISSUE THREAD

**Issue by AgustinSanchez00** [Pauan/blender-rigid-body-bones#17]
the bones will explode and it never resets, all attempts to reset bones or collisions do not work.

**Comment by Pauan** [comment]
Strange... let me figure out what the problem is...

**Comment by Pauan** [comment]
Alright, I released version 1.6.2 which fixes the error, thanks for the report:

https://github.com/Pauan/blender-rigid-body-bones/releases/tag/v1.6.2

**Comment by PAHANrus2** [comment]
still now working, all bones crashed when you install addon, im trying install on clear 3.4.1 and 3.5 version blender. also examples files not working

**Comment by PAHANrus2** [comment]
![image](https://user-images.githubusercontent.com/132598802/236269870-eb96dc61-eef0-4709-9148-9f349e6d8953.png)
![image](https://user-images.githubusercontent.com/132598802/236270015-e94c293f-8ca1-4a5f-b5e5-5cbd16e9c212.png)
that happening

**Comment by Pauan** [comment]
Have you tried unchecking and re-checking the `Enable rigid body physics` checkbox?

![Usage 04](https://user-images.githubusercontent.com/97238/236596525-19b02540-bc30-4832-b2a4-07e4fe64cf51.PNG)

Also make sure that you click the `Delete All Bakes` button.

**Comment by PAHANrus2** [comment]
> Have you tried unchecking and re-checking the `Enable rigid body physics` checkbox?
> 
> ![Usage 04](https://user-images.githubusercontent.com/97238/236596525-19b02540-bc30-4832-b2a4-07e4fe64cf51.PNG)
> 
> Also make sure that you click the `Delete All Bakes` button.

Okey im get it how its work, guys who used you need in pose mode refresh " enable rigid body physics " then is work. and also how to stay bones on the scene without falling? okey im think you need last empty bone without any "RIGID BODY SETTING. If you doing this 
![image](https://github.com/Pauan/blender-rigid-body-bones/assets/132598802/945f3d08-35ab-494a-8241-7ab13ad108ee)
that happened 
![image](https://github.com/Pauan/blender-rigid-body-bones/assets/132598802/74479c03-d73b-40aa-a956-744e19fe5a9e)

So you need doing this! 
![image](https://github.com/Pauan/blender-rigid-body-bones/assets/132598802/98686236-2b5b-45b3-ae8f-f8251f87f010)
and that work
![image](https://github.com/Pauan/blender-rigid-body-bones/assets/132598802/96f16f0b-7003-4afc-a155-a1e8bda91217)
and try to see the examples from the author. just refresh rigid body phys, anyway please author fix this in next update.
