### ISSUE TITLE
How to bake to animation?

### ISSUE THREAD

**Issue by liunliun** [Pauan/blender-rigid-body-bones#3]
Its works very well but a little question,How to bake to animation?
I try to inserted key at the frame when i want,but the movement will be mess up after I inserted a key

**Comment by liunliun** [comment]
these three buttons "Bake all dynamics" "Update to frame" "calculate to frame" are not working.

**Comment by Pauan** [comment]
This feature just hasn't been implemented yet, since it's tricky to do, but it's on my todo list.

**Comment by Pauan** [comment]
Version 1.4 now has a `Pose -> Rigid Body -> Bake to Keyframes` operator which bakes the selected Active bones to keyframes.
