### ISSUE TITLE
Your addon does not appear in the Addons tab in Blender.

### ISSUE THREAD

**Issue by milkix2** [Pauan/blender-rigid-body-bones#8]
I tried installing the 1.6.1 and 1.6.0 version add-ons. Your addon does not appear in the Addons tab in Blender. 
How can we solve this problem? I tried all of them in Blender version 2.91, 2.92, 2.93 and got the same result. 
![이미지 1632223300](https://user-images.githubusercontent.com/91128885/134162672-ee6b5af4-5766-4a4a-85d9-73dbd681c41b.jpg)

**Comment by Pauan** [comment]
You must have an Armature selected. This add-on only handles bones, nothing else, so it only works with Armatures.
